// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI (migrate/studio) prefers a direct, non-pooled connection.
    // Falls back to DATABASE_URL for local dev, where only one URL exists.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
